services:
  postgres:
    image: postgres:16
    container_name: ordertracker-db
    environment:
      POSTGRES_DB: ordertracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2025
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: ordertracker-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ordertracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 2025