spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ordertracker
    username: postgres
    password: 2025

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: OrderTracker

server:
  port: 8080
kind: Application