spring.application.name=OrderTracker
jwt.secret=myverysecretkeymyverysecretkey1234567890

logging.level.org.hibernate.SQL=DEBUG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=docflow.api.system2026@gmail.com
spring.mail.password="qrvt fpsp azlt uyfz"

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true